### ISSUE TITLE
“Bleed” is bleeding on larger screen sizes

### ISSUE THREAD

**Issue by yansusanto** [shuding/nextra#2923]
The <`Bleed`> component is `bleeding` too much on both edges with `-mx-24` on screen resolution **higher than 1600x900** (20" desktop), thus overlapping the sidebar on both sides.

May I suggest that we use `-mx-12` instead?

![Bleed-–-Nextra](https://github.com/shuding/nextra/assets/2361743/fb0d2769-5cdf-4019-9555-22171f1a710a)

---

### Versions

```
"next": "^13.0.6",
"nextra": "^3.0.0-alpha.24",
"nextra-theme-docs": "^3.0.0-alpha.24",
```

**Comment by dimaMachina** [comment]
this was fixed in v3 https://github.com/shuding/nextra/pull/2866 https://nextra-v2-9c3amvff4-shud.vercel.app/docs/docs-theme/built-ins/bleed can you confirm in preview deployment?

**Comment by yansusanto** [comment]
No it is not fixed yet here https://nextra-v2-9c3amvff4-shud.vercel.app/docs/docs-theme/built-ins/bleed.  

<img width="1469" alt="Screenshot 2024-06-08 at 8 46 28 PM" src="https://github.com/shuding/nextra/assets/2361743/4d6321c3-1289-444b-8e8b-9d0ddbc227f8">

**Comment by dimaMachina** [comment]
This is intentional behaviour

**Comment by yansusanto** [comment]
Noted with thanks. Would it be better if we make the negative margin smaller so that it doesn't overlap the sidebar?

**Comment by mengxi-ream** [comment]
You can customize your Bleed use `-mx-6` like
```tsx
      <div className="relative mt-6 -mx-6 sm:mx-0 rounded-none sm:rounded-xl border-y sm:border border-zinc-200 dark:border-zinc-800 overflow-hidden">
        {children}
      </div>
```

**Comment by dimaMachina** [comment]
closing since it was per design
