### ISSUE TITLE
Underlined dash separators appear on Vercel builds

### ISSUE THREAD

**Issue by M4dmax01** [shuding/nextra#4837]
Describe the bug
On Vercel deployments (but not local dev), Nextra 4’s with next.js 14 default x:lg:after:content-["–"] utility adds a pseudo-element dash to header controls (nav items, search box, “Copy page” button, etc.). The pseudo-element inherits text-decoration: underline, so it renders as a visible underscore between controls.

To Reproduce

Scaffold a docs site with nextra-theme-docs 4.6.0.
Deploy to Vercel (shallow clone, default settings).
Open the deployed docs page in Chrome on desktop (>1024px).
Notice the underscores between navbar items/search/hamburger, even though they’re absent in npm run dev.
Expected behavior
UI should match local dev: the separator pseudo-element shouldn’t inherit underline, or it should be configurable so it doesn’t appear.

Screenshots
(Screenshot showing underscores between “Vue d’ensemble / Authentification / Endpoints / search / hamburger” on the Vercel deployment.)

Desktop

OS: Windows 11
Browser: Chrome Version 142.0.7444.134 (Official Build) (64-bit)
Smartphone
N/A (only at desktop breakpoint)

Additional context
The dash comes from .x:lg:after:content-["–"] in nextra-theme-docs/dist/style-prefixed.css. Locally we can override it, but Vercel’s bundled CSS (or load order) causes the underline to persist, so even runtime overrides struggle. Exposing a toggle or preventing underline inheritance would prevent this discrepancy between dev and Vercel builds.

<img width="1875" height="850" alt="Image" src="https://github.com/user-attachments/assets/5f9507f2-c38b-4291-8b65-a2f5d2708b5f" />

The underscore are showen in the header and in the other elements of the page

**Comment by omeroot** [comment]
i have same issue. But it is not only vercel, if you build `next build` and `next start` in your local machine you can see same issue. 

I have investigated what is reason of issue, some stylings in `nextra-theme-docs/style.css` not working. for example .x:md:hidden is looking empty style in developer tool.

<img width="1206" height="324" alt="Image" src="https://github.com/user-attachments/assets/b2368830-06d8-4992-9d10-c7d8643c38ab" />

**Comment by omeroot** [comment]
I have fixed by version upgrade 🎉:

new versions in package.json:
```json
{
  "next": "^16.0.3",
  "next-themes": "^0.4.6",
  "nextra": "^4.6.0",
  "nextra-theme-docs": "^4.6.0",
  "react": "^19.2.0",
  "react-dom": "^19.2.0",
}
```

There is a Next.js 15+ breaking change. In Next.js 15, params and searchParams are now Promises and must be awaited.

Change your `[[...mdxPath]]/page.tsx` with 

```jsx
import { generateStaticParamsFor, importPage } from 'nextra/pages';

import { useMDXComponents as getMDXComponents } from '../../../../mdx-components';

export const generateStaticParams = generateStaticParamsFor('mdxPath');

interface GenerateMetadataProps {
  params: {
    mdxPath: string[];
  };
}

export async function generateMetadata(props: GenerateMetadataProps) {
  const { params } = props;
  const { metadata } = await importPage(params.mdxPath);
  return metadata;
}

const Wrapper = getMDXComponents().wrapper;

interface PageProps {
  params: Promise<{ mdxPath: string[] }>;
}

export default async function Page(props: PageProps) {
  const { params } = props;
  const { mdxPath } = await params; // ✅ Await params first

  const {
    default: MDXContent,
    toc,
    metadata,
    sourceCode,
  } = await importPage(mdxPath);
  return (
    <Wrapper toc={toc} metadata={metadata} sourceCode={sourceCode}>
      <MDXContent {...props} params={params} />
    </Wrapper>
  );
}
```

you can look at [AppCatalystRN](https://www.appcatalystrn.com/docs)

**Comment by M4dmax01** [comment]
Hello thanks for the help man, I did your fix it didn't work for me, I have this in my package.json:

```
{
    "next": "^14.2.14",
    "nextra": "^4.6.0",
    "nextra-theme-docs": "^4.6.0",
    "next-themes": "^0.4.6",
     "react": "^18.3.1",
    "react-dom": "^18.3.1",
}
```

I changed my page.tsx to this and i still have the same problem in Vercel in local it works correctly :
```
//\docs\[[...mdxPath]]\page.tsx
import { generateStaticParamsFor, importPage } from "nextra/pages";
import { useMDXComponents } from "@/mdx-components";
import type { Metadata } from "next";
import type { MDXWrapper } from "nextra";

const DefaultWrapper: MDXWrapper = ({ children }) => <>{children}</>;
const components = useMDXComponents({});
const Wrapper: MDXWrapper =
  (components.wrapper as MDXWrapper | undefined) ?? DefaultWrapper;

export const generateStaticParams = generateStaticParamsFor("mdxPath");
export const dynamic = "force-static";
export const dynamicParams = false;

function normalizeMdxPath(params: { mdxPath?: string[] }) {
  const mdxPath = params?.mdxPath;
  if (!mdxPath || mdxPath.length === 0) {
    return [];
  }
  return mdxPath;
}

export async function generateMetadata({
  params,
}: {
  params: { mdxPath?: string[] };
}): Promise<Metadata> {
  const { metadata } = await importPage(normalizeMdxPath(params));
  return metadata ?? {};
}

interface PageProps {
  params: Promise<{ mdxPath: string[] }>;
}

export default async function DocsPage(props: PageProps) {
  const { params } = props;
  const { mdxPath } = await params;

  const {
    default: MDXContent,
    toc,
    metadata,
    sourceCode,
  } = await importPage(mdxPath);
  return (
    <Wrapper toc={toc} metadata={metadata} sourceCode={sourceCode}>
      <MDXContent {...props} params={params} />
    </Wrapper>
  );
}
```

It actually the ::after that cause that are rendered as underscore i checked the console and it this attributes :

```
   --tw-content: "–";
   content: var(--tw-content);
```

<img width="459" height="313" alt="Image" src="https://github.com/user-attachments/assets/be951a90-ff7a-4369-a3fc-fe3ed4571964" />

Do you have any other idea that may cause this please thanks for your effort.

**Comment by dimaMachina** [comment]
@M4dmax01
update your next.js app to v15 or v16
